### PR TITLE
add nida filename and study handling, and add tests

### PR DESCRIPTION
**Pull request by warrenstephens**

### CODE REVIEW

**Review by cschreep — CHANGES_REQUESTED** [review]
Why is this a separate PR from https://github.com/helxplatform/dug/pull/177 ?

**Comment by warrenstephens** [comment]
> Why is this a separate PR from #177 ?

I was planning to cancel the other PR.

**Comment by cschreep** [comment]
I think it would probably be cleaner to keep making changes on that branch and PR, reduce the amount of clutter, keep a clear audit trail, preserve conversations, etc.

**Comment by warrenstephens** [comment]
My laptop migration made things a little wonky to continue where I left off, but I can figure out how to resurrect it if need be.

**Comment by cschreep** [comment]
Right, let's consolidate it to one feature branch and PR

**Pull request merged**
