### PR TITLE
Adding python testing instructions and initial tests

### PR DESCRIPTION
**Pull request by andrew-rti**

### CODE REVIEW

**Comment by andrew-rti** [comment]
Worth noting--I've removed some trailing spaces from a couple files

**Comment by cmball1** [comment]
@andrew-rti Did you have to run `python setup.py install` for kgx? I just had to run `bin/dug dev init` and that also executed the code on line 60 of `bin/dug` that clones the kgx repo.

Would it be good to have `bin/dug dev init` install the requirements.txt and clone the kgx repo, then have `bin/dug` exit if kgx is not installed in place of where it is currently cloning kgx on line 60? @alexwaldrop what do you think?

Did you run a linter that changed the trailing spaces?

**Comment by cmball1** [comment]
@stevencox this is a first test for the `Debreviator` class in `annotate.py` to set up the file and import for unit tests for the functions. @andrew-rti is going to open a new PR to add running the tests in a bash script to match the way we have the function calls set up in `bin/`.

**Comment by andrew-rti** [comment]
@cmball1 I did run the `python` command however i'll checkout the `bin/dug dev init` function. I think all that sounds good however I'm not sure I'm tracking on the install/clone statement? Why would the install location be different from the clone location if they're running dev init?

For the spaces I have a macro defined for vim that I run if I notice trailing or unnecessary whitespace.

**Pull request merged**
