### PR TITLE
Dug interface

### PR DESCRIPTION
**Pull request by cschreep**
This PR adds a Dug class to serve as the main Python entrypoint to Dug. It also significantly expands the CLI both for readability and to use the Dug class.

### CODE REVIEW

**Review by alexwaldrop — CHANGES_REQUESTED** [review]
I'm ready to accept once we get the search_kg(), search_nboost(), agg_data_type() funcitionality implemented. Also, we need to make sure this doesn't break any of the endpoints in api.py, because as is I think it will break those endpoints and thus also break the dug-search-client

**Comment by jcheadle-rti** [comment]
Would echo Alex's comments that this needs to be tested with the UI integrated.

**Review by jcheadle-rti — COMMENTED** [review]
Would echo Alex's comments that this needs to be tested to make sure UI works with this new structure.

**Comment by cschreep** [comment]
With regards to the API, the API only consumes the Search class directly. This PR doesn't make any changes to that class so

**Comment by cschreep** [comment]
@alexwaldrop @jcheadle-rti I added the wrapper for the search-kg and search-nboost.

**Review by jcheadle-rti — APPROVED** [review]

**Review by alexwaldrop — APPROVED** [review]

**Pull request merged**
