### PR TITLE
release 2.7

### PR DESCRIPTION
**Pull request by cschreep**

### CODE REVIEW

**Comment by cschreep** [comment]
Something's up with parsing the study name in the scicrunch parser

**Comment by cschreep** [comment]
Everything checks out, this PR is ready for review @HowardLander @warrenstephens @alexwaldrop @jcheadle-rti @YaphetKG

**Review by HowardLander — APPROVED** [review]

**Review by YaphetKG — APPROVED** [review]
LGTM!

**Review by warrenstephens — APPROVED** [review]
I don't see a corresponding change for "-> Optional[Identifier]:" -- but that is Ok when I think about it.

**Pull request merged**
