### PR TITLE
Ncpi index fix

### PR DESCRIPTION
**Pull request by alexwaldrop**

### CODE REVIEW

**Comment by YaphetKG** [comment]
Thanks Alex, so this means for this new round we are expecting a single gz file with sub directories denoting the types ?

**Comment by alexwaldrop** [comment]
> means

**Comment by YaphetKG** [comment]
Hi @alexwaldrop that sounds good to me, keeping the original files separate  BDC files separate from NCPI new datasets. I was a little unclear on the structure of NCPI datasets, I see that there is a folder structure in this new tar ball, is that the way we know the different types that are under the NCPI (Anvil , KFDRC, CDRC etc...) ? 

From the setup in airflow currently we are using a single tar file as an input to the tasks, so this means we can easily add more tar inputs and map them to a parser in roger, as an example for anvil Here is the [file fetcher code](https://github.com/helxplatform/roger/blob/08e65c71b47b36f651973f84afd29ccc95ea35fb/dags/dug_helpers/dug_utils.py#L846) and [the annotation task](https://github.com/helxplatform/roger/blob/develop/dags/dug_helpers/dug_utils.py#L594-L602) , 

This is setup so that since our unit of data currently is a tar file (or Topmed sets), and we are able to parallelize at that level. I think if we group all NCPI into one tar file we would loose that. 

As a remedy if we just tar them at the `platform` level I think we can easily achieve that, what do you think?

**Comment by alexwaldrop** [comment]
@YaphetKG just updated to make the each NCPI source it's own tarball directory in the data folder. Should be good to merge!

**Pull request merged**
